config/routes.rb
GuestBook::Application.routes.draw do
  
  resources :people
  root :to=>"people#index"
  post "admin" => "sessions#new"
  resources :sessions,only: [:new, :create, :destroy]
  get "admin" => "sessions#new"
  get "logout" => "sessions#destroy"

end

app/models/person.rb
class Person < ActiveRecord::Base
	attr_accessible :name, :message 
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :password, :password_confirmation 
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  	session[:user_id] ? @current_user ||= User.find(session[:user_id]) : nil
  end

  private

  def require_login
  	unless current_user
  		redirect_to sessions_path
  	end
  end
end

app/controllers/people_controller.rb
# encoding: UTF-8
class PeopleController < ApplicationController
	before_action :require_login, only: [:destroy]

	def index
		@people = Person.all
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)

		if @person.name.empty? or @person.message.empty?
			redirect_to new_person_url
			flash[:error] = 'İsim Veya Mesaj Kısmı Boş Bırakılmaz !'
		else
			if @person.save
				redirect_to people_url
			else
				flash[:error] = 'Mesaj Kaydedilemedi !'
				render "new"
			end
		end
	end

	def destroy
		@person = Person.find(params[:id])

		if @person.present?
			@person.destroy
		end

		redirect_to people_url
	end

	private
	
	def set_person
		@person = Person.find(params[:id])
	end


	def person_params
		params.require(:person).permit(:id, :name, :message)
	end
end

app/controllers/sessions_controller.rb
# encoding: UTF-8

class SessionsController < ApplicationController

  def new
  	redirect_to people_path and return if current_user
  end

  def create
  	user = User.find_by_name(params[:name])
  	
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to people_path
  	else
  		flash[:error_admin] = "Kullanici adin ve/veya parolan hatali"
  		redirect_to admin_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to admin_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		session[:user_id] ? @current_user ||= User.find(session[:user_id]) : nil 
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GuestBook</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top navbar-inverse" >
		<div class="navbar-inner" >
			<div class="container" >
				<div class="navbar-header">
					<a href="/" class="navbar-brand" style="font-size:25px;position:relative;top:-20px;right:100px;"> <%= image_tag "book.png" %>MİSAFİR DEFTERİ </a>
				</div>
				<div class="navbar-collapse collapse" id="navbar-main">

					<ul class="nav navbar-nav navbar-right">
						<a href="<%= new_person_path %>" class="navbar-brand" style="position:relative;top:-10px"><%= image_tag "mesaj.png" %>Yeni Mesaj</a>
						<% if current_user %>
						<a href="<%= logout_path %>" class="navbar-brand" > Çıkış </a>
						<% end %>

					</ul>
				</div>
			</div>
		</div>
	</div>

	<%= yield %>

	<div class="navbar-fixed-bottom" style="height:35px;">
		<div class="navbar navbar-inverse" style = "margin-bottom: 0px;">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav pull-right">
						<a href="#" class="navbar-brand" style = "position:absolute;left:5in; top:-10px;font-size:15px;">©2014 - Betül SARAL, Tuğba DEVRAVUT </a>
					</ul>
				</div>
			</div>
		</div>
	</div>    
</body>
</html>

app/views/people/_form.html.erb
<div class="hero-unit" style="position:absolute;top:100px;left:4.3in;width:auto;">
	<div id = "kutu" style = "background-color:#485680;width:5in;height:50px;text-align:center;">
		<h3 style ="position:relative;top:10px;color:white"> YENİ MESAJ </h3>
	</div><br><br>

	<%= form_for @person, :html => {:class => "form-inline"} do |f| %>
		<% if flash[:error] %>
		<div class = "alert alert-warning" style="width:4in;position:relative;left:0px;top:-10px">
			<%= flash[:error] %>
		</div>
		<% end %>
		<div class="input-group" style="width:5in;">
			<span class="input-group-addon">Ad-Soyad</span>
			<%= f.text_field :name,:class=>"form-control"%>
		</div><br><br>
		<div class="input-group" style="width:5in;">
			<span class="input-group-addon">Mesaj</span>
			<%= f.text_area :message,:class=>"form-control",:cols => 10, :rows => 7%>
		</div>
		<div class="actions">
			<%= f.submit "Gönder", class: 'btn btn-primary', style: "width:2in;position:relative;top:30px;left:3in"%>
		</div>
	<% end %>
</div>

app/views/people/index.html.erb
<div class="hero-unit" style="position:absolute;top:120px;left:4in;width:auto;">
	<% @people.each do |person| %>
		<div id = "kutu" style = "background-color:#485680;width:6.2in;height:auto;">
			<% if current_user %>
				<b style="color:white;text-transform:uppercase;position:relative;top:10px;left:20px;font-size:18px;"><%=person.name %> :</b> <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, style: "color:white;float:right", class: "btn btn-danger" %>
			<% else %>
				<b style="color:white;text-transform:uppercase;position:relative;top:10px;left:20px;font-size:18px;"><%=person.name %> :</b>
			<% end %>
			<br><br><p style="color:white;text-transform:capitalize;position:relative;left:20px;font-size:15px;padding-right:50px;"> <%= person.message %> </p><br>
			
		</div><br><br><br>
	<% end %>
</div><br><br><br><br>

app/views/people/new.html.erb
<%= render 'form' %>